#!/bin/bash
if [ ! -f /var/run/scrubber ]; then
  exit 0
fi

if [ -f /boot/config/plugins/scrubber/settings.cfg ]; then
  SIMULTANEOUS="$(cat /boot/config/plugins/scrubber/settings.cfg | grep "SIMULTANEOUS" | cut -d '=' -f2 | sed 's/"//g')"
  WAIT="$(cat /boot/config/plugins/scrubber/settings.cfg | grep "WAIT" | cut -d '=' -f2 | sed 's/"//g')"
else
  SIMULTANEOUS="true"
  WAIT=5
fi

if [[ -n "$WAIT" && "$WAIT" -ne 0 ]]; then
  logger "BTRFS Scrubber: Waiting ${WAIT} seconds before continuing..."
  sleep ${WAIT}s
fi

while IFS= read -r line; do
  if [ "${SIMULTANEOUS}" != "true" ]; then
    logger "BTRFS Scrubber: Starting non simultaneous Scrub on BTRFS Pool: ${line}"
    btrfs scrub start /mnt/${line}
    sleep 2
    while true; do
      SCRUB_STATE="$(btrfs scrub status /mnt/${line} | grep "Status:" | awk '{print $2}')"
      if [ "${SCRUB_STATE}" == "running" ]; then
        sleep 10
      else
        logger "BTRFS Scrubber: Scrub on BTRFS Pool: ${line} done!"
        SCRUB_FINISHED="$(btrfs scrub status /mnt/${line})"
        SCRUB_SUMMARY="$(grep "Error summary:" <<< "${SCRUB_FINISHED}")"
        if grep -q "no errors" <<< "${SCRUB_SUMMARY}" ; then
          IMPORTANCE="normal"
        else
          IMPORTANCE="alert"
        fi
        /usr/local/emhttp/plugins/dynamix/scripts/notify -e "BTRFS Scrubber" -s "BTRFS Scrub on Pool: ${line} finished!" -d "$(echo "${SCRUB_FINISHED}" | awk '{printf "%s<br/>", $0}')" -i ${IMPORTANCE}
        unset SCRUB_STATE SCRUB_FINISHED SCRUB_SUMMARY IMPORTANCE
        break
      fi
    done
  else
    logger "BTRFS Scrubber: Starting Scrub on BTRFS Pool: ${line}"
    echo "/usr/local/emhttp/plugins/scrubber/scripts/notify.sh \"${line}\"" | at now -M > /dev/null 2>&1
    btrfs scrub start /mnt/${line}
  fi
done <<< $(cat /var/run/scrubber)

rm -f /var/run/scrubber